import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, ArrowRight, BatteryCharging, Sun, Wind, Droplets, Menu, X, MapPin, Phone, MessageCircle, ClipboardList, Wrench, Pause, Play, ChevronRight } from 'lucide-react';
import { PHONE, QUOTE_URL, SERVICE_URL, services } from './data';
import type { ServiceId } from './data';
import HeroScene from './HeroScene';
const icons = { solar:Sun, battery:BatteryCharging, comfort:Wind, water:Droplets };
function useReducedMotion() {
 const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const q=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(q.matches);q.addEventListener('change',update);return()=>q.removeEventListener('change',update)},[]);return reduced;
}
function Device({type}:{type:ServiceId}) {return <div className={`device device-${type}`} aria-hidden="true"/>}
function App(){
 const [active,setActive]=useState<ServiceId>('solar');const [menu,setMenu]=useState(false);const reduced=useReducedMotion();const [paused,setPaused]=useState(false);const [inView,setInView]=useState(true);const hero=useRef<HTMLElement>(null);const tabs=useRef<(HTMLButtonElement|null)[]>([]);const selected=services.find(s=>s.id===active)!;const Icon=icons[active];
 const [choice,setChoice]=useState('solar');const [suburb,setSuburb]=useState('');const [quoteReady,setQuoteReady]=useState(false);
 useEffect(()=>{const io=new IntersectionObserver(([e])=>setInView(e.isIntersecting),{threshold:0.05});if(hero.current)io.observe(hero.current);return()=>io.disconnect()},[]);
 useEffect(()=>{const els=document.querySelectorAll('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');io.unobserve(e.target)}}),{threshold:0.1});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu]);
 const closeMenu=()=>setMenu(false);
 return <>
 <a className="skip-link" href="#solutions">Skip to content</a>
 <header className="header"><a className="brand" href="#home" aria-label="Sharpe En3rgy Solutions home"><img src="/images/logo.webp" alt="Sharpe En3rgy Solutions" width="600" height="190"/></a><nav aria-label="Main navigation" className={menu?'nav nav-open':'nav'}><a href="#solar-battery" onClick={closeMenu}>Solar & batteries</a><a href="#solutions" onClick={closeMenu}>Home comfort</a><a href="#about" onClick={closeMenu}>Our people</a><a className="button button-small" href={QUOTE_URL}>Get a quote <ArrowUpRight size={15}/></a></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main>
 <section className="hero" id="home" ref={hero} aria-labelledby="hero-heading">
 <div className="hero-atmosphere"/><div className="hero-glow"/>
 <div className="hero-copy"><h1 id="hero-heading">Your home.<br/><em>Powered smarter.</em></h1><p className="hero-subtitle">Solar, batteries and comfort for Adelaide homes.</p><div className="hero-actions"><a className="button" href={QUOTE_URL}>Get a quote <ArrowUpRight size={17}/></a><a className="button button-glass" href={SERVICE_URL}>Book a service <ArrowRight size={17}/></a></div></div>
 <div className="home-experience"><HeroScene active={active} paused={paused||reduced||!inView} onSelect={setActive}/>
 <button className={`floating-card float-solar ${active==='solar'?'current':''}`} onClick={()=>setActive('solar')} aria-pressed={active==='solar'}><span className="mini-eyebrow">01 / GENERATE</span><h3>Solar</h3><p>Good energy.<br/>From your own roof.</p><Device type="solar"/><span className="card-corner"><ArrowUpRight size={15}/></span></button>
 <button className={`floating-card float-battery ${active==='battery'?'current':''}`} onClick={()=>setActive('battery')} aria-pressed={active==='battery'}><span className="mini-eyebrow">02 / STORE</span><h3>Battery</h3><p>Your sunshine.<br/>After sunset.</p><Device type="battery"/><span className="card-corner"><ArrowUpRight size={15}/></span></button>
 <button className={`floating-card float-comfort ${active==='comfort'?'current':''}`} onClick={()=>setActive('comfort')} aria-pressed={active==='comfort'}><span className="mini-eyebrow">03 / FEEL</span><h3>Comfort</h3><p>A better feeling.<br/>In every season.</p><Device type="comfort"/><span className="card-corner"><ArrowUpRight size={15}/></span></button>
 <div className="scene-caption" aria-live="polite"><Icon size={16}/><span>{selected.title}</span><span className="caption-dot"/>{selected.short}</div>
 </div>
 <div className="explorer-controls"><div className="service-tabs" role="tablist" aria-label="Explore your home">{services.map((s,i)=><button key={s.id} ref={el=>{tabs.current[i]=el}} id={`tab-${s.id}`} role="tab" aria-selected={active===s.id} aria-controls="service-detail" tabIndex={active===s.id?0:-1} onClick={()=>setActive(s.id)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%4;else if(e.key==='ArrowLeft')next=(i+3)%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();setActive(services[next].id);tabs.current[next]?.focus()}}>{s.label}</button>)}</div><button className="motion-toggle" onClick={()=>setPaused(!paused)} disabled={reduced} aria-label={paused?'Resume gentle motion':'Pause gentle motion'}>{paused||reduced?<Play size={14}/>:<Pause size={14}/>}</button></div>
 <div className="explorer-detail" id="service-detail" role="tabpanel" aria-labelledby={`tab-${active}`}><span>{selected.short}</span><a href={`#${active}`}>Explore {selected.label.toLowerCase()} <ArrowUpRight size={14}/></a></div>
 <a className="scroll-cue" href="#solutions"><span>Explore your home</span><ArrowDown size={17}/></a>
 </section>
 <section className="solutions soft-section" id="solutions" aria-labelledby="solutions-title"><div className="section-photo"/><div className="solutions-shade"/><div className="container solutions-layout"><div className="section-intro reveal"><p className="eyebrow light"><span/> ONE CONNECTED HOME</p><h2 id="solutions-title">One home.<br/>Connected<br/>solutions.</h2><p>A smarter, more comfortable and more efficient home, all working together.</p><a className="text-link light-link" href={QUOTE_URL}>Let’s talk about your home <ArrowUpRight size={18}/></a></div><div className="services-grid">{services.map((s,i)=>{const I=icons[s.id];return <a className="service-card glass reveal" href={s.url} key={s.id} id={s.id} style={{transitionDelay:`${i*60}ms`}}><div className="service-top"><I size={20}/><span>0{i+1}</span></div><Device type={s.id}/><div><h3>{s.title}</h3><p>{s.short}</p></div><ArrowUpRight className="service-arrow" size={19}/></a>})}</div></div></section>
 <section className="solar-feature cream soft-section" id="solar-battery"><div className="container feature-layout"><div className="feature-image reveal"><img src="/images/solar-roof.webp" alt="Illustrative rooftop solar panels in Adelaide sunshine" width="1672" height="941" loading="lazy"/><div className="image-note glass"><div><strong>Battery storage</strong><p>Store excess solar<br/>and use it when<br/>you need it.</p></div><Device type="battery"/></div></div><div className="feature-copy reveal"><span className="feature-number" aria-hidden="true">01</span><h2>Make more<br/>of your solar.</h2><p>Find a solar and battery solution tailored to your home.</p><a className="text-link" href={QUOTE_URL}>Explore Solar & Batteries <ArrowUpRight size={18}/></a><div className="feature-points"><span><Sun size={17}/> Energy from your roof</span><span><BatteryCharging size={17}/> Storage for later</span></div></div></div></section>
 <section className="process soft-section" id="process"><div className="section-photo"/><div className="process-shade"/><div className="container"><div className="process-heading reveal"><p className="eyebrow light"><span/> SIMPLE FROM THE START</p><h2>From first conversation<br/>to a better home.</h2><p>Good advice. The right fit. Support along the way.</p></div><div className="steps">{[{n:'01',title:'Talk to us',text:'Your routine, your space and what you want to improve. We start by listening.',I:MessageCircle},{n:'02',title:'Find your solution',text:'Explore solar, storage and comfort options suited to the way you live.',I:ClipboardList},{n:'03',title:'Installation & support',text:'Arrange installation or service, with a team you can come back to for support.',I:Wrench}].map(({n,title,text,I})=><article className="step glass reveal" key={n}><div><span className="step-number">{n}</span><I size={27}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="about cream soft-section" id="about"><div className="container about-layout"><div className="about-copy reveal"><p className="eyebrow"><span/> RIGHT HERE IN ADELAIDE</p><h2>Local people.<br/>Practical advice.</h2><p>Helping Adelaide homeowners choose the right solution.</p><a className="text-link" href="tel:+61882946333">Talk to the team <ArrowUpRight size={18}/></a><div className="location-pill"><MapPin size={18}/><span>49 Port Road, Thebarton<br/><small>Adelaide, South Australia</small></span></div></div><div className="about-image reveal"><img src="/images/team.webp" alt="En3rgy Solutions technician working on rooftop solar, from the company's website" width="1000" height="667" loading="lazy"/><span className="photo-label glass">GOOD ENERGY STARTS WITH GOOD PEOPLE</span></div></div></section>
 <section className="service-banner soft-section"><div className="container banner-layout"><div className="reveal"><p className="eyebrow light"><span/> SERVICE & SUPPORT</p><h2>Keep your home<br/>working at its best.</h2><p>Efficient, reliable air conditioning<br/>for year round comfort.</p><a className="button" href={SERVICE_URL}>Book a service <ArrowUpRight size={18}/></a></div></div></section>
 <section className="quote cream soft-section" id="quote"><div className="container quote-layout"><div className="reveal"><p className="eyebrow"><span/> YOUR NEXT STEP</p><h2>Let’s power<br/>your next step.</h2><p>Tell us about your home and what you need.</p><a className="phone-link" href={PHONE}><Phone size={18}/> (08) 8294 6333</a></div><div className="quote-card reveal"><form onSubmit={e=>{e.preventDefault();setQuoteReady(true)}}><label htmlFor="quote-service">What can we help you with?</label><select id="quote-service" value={choice} onChange={e=>{setChoice(e.target.value);setQuoteReady(false)}}>{services.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}<option value="several">More than one service</option></select><label htmlFor="suburb">Your suburb <span>(optional)</span></label><input id="suburb" placeholder="e.g. Bowden" autoComplete="address-level2" maxLength={80} value={suburb} onChange={e=>setSuburb(e.target.value)}/><button className="button" type="submit">Find my next step <ArrowRight size={18}/></button></form>{quoteReady?<div className="quote-result" aria-live="polite"><strong>{choice==='several'?'A connected home starts with a conversation.':`${services.find(s=>s.id===choice)?.title}: let’s explore your options.`}</strong><p>{suburb.trim()?`For your home in ${suburb.trim()}, the team can discuss a tailored solution.`:'The team can help you find a solution suited to your home.'}</p><a className="text-link" href={QUOTE_URL}>Continue to the official quote form <ArrowUpRight size={17}/></a></div>:<p className="form-note">Complete your request through the company’s official booking system in the next step.</p>}</div></div></section>
 </main>
 <footer><div className="container footer-top"><a href="#home" className="footer-brand"><img src="/images/logo.webp" alt="Sharpe En3rgy Solutions" width="600" height="190" loading="lazy"/></a><div><span>ADELAIDE, SOUTH AUSTRALIA</span><p>Solar · Batteries · Comfort · Hot water</p></div><a href={PHONE} className="text-link light-link">Let’s talk <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><p>Independent design concept by <a href="https://lucasderossa.dev/">Lucas De Rossa</a>. Illustrative home imagery.</p><a href="https://en3rgy.au/">Visit the current company website <ChevronRight size={13}/></a></div></footer>
 </>
}
export default App;
